### ISSUE TITLE
[BUG] Audits no filtra collaborators disabled

### ISSUE THREAD

**Issue by Sealra** [caverav/auditforge#125]
**Descripción del bug**
Al editar un audit, el campo de collaborators solo debería permitir agregar a colaboradores 'enabled'

**Cómo reproducir**
Pasos para reproducir:
1. Agregar collaborator
2. Deshabilitarlo a través del modal de edición
3. Ingresar a un Audit
4. Ver el dropdown de collaborators

**Comportamiento esperado**
Que sólo estén los collaborators enabled en el dropdown.

**Entorno:**
 - OS: Pop OS! 22.04
 - Browser: MS Edge

**Comment by Sealra** [comment]
Si esto es el comportamiento esperado por favor indicarlo!

**Comment by caverav** [comment]
Esto se conversó en reunión, y es comportamiento esperado, lo cerraré

**Comment by Sealra** [comment]
Oka 👍
