### ISSUE TITLE
[FEAT] Update findings listing on audit sidebar

### ISSUE THREAD

**Issue by jllanosg** [caverav/auditforge#147]
**Está relacionada a un problema? Descríbelo**

Al agregar un finding a un audit no se actualiza el sidebar

**Describe la solución que te gustaría**

Que se actualice el sidebar cada vez que se agregue un nuevo finding al audit.

**Describe alternativas que has considerado**
n/a

**Contexto adicional**
n/a

**Comment by iTzGooDLife** [comment]
Resuelto en el PR https://github.com/caverav/auditforge/pull/163#issue-2631558498
